/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentdatabase;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import java.sql.PreparedStatement;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import studentdatabase.data.DataAccess;
import studentdatabase.model.*;
import studentdatabase.model.controller.Controller;
import studentdatabase.model.Student;
import java.util.List;
import studentdatabase.data.DBInstance;

/**
 *
 * @author elshaday
 */
public class OmnilyfDatabase extends javax.swing.JFrame {

    Controller controller;
   
    DefaultTableModel model = new DefaultTableModel();
    List<Career> careers = new ArrayList();
    List<Student> students = new ArrayList();
    /**
     * Creates new form OmnilyfDatabase
     */
    public OmnilyfDatabase() throws SQLException {
        
        initComponents();
        setTitle("Omnilyf Student Database");
       
        controller = new Controller();

        Object col[] = {"FirstName", "LastName", "Email", "Phone Number"};
        model.setColumnIdentifiers(col);
        jTable1.setModel(model);
        
        term1.setText(controller.getTerms().get(0).getStartDate().toString()+ " - " + controller.getTerms().get(0).getEndDate().toString() );
        term2.setText(controller.getTerms().get(1).getStartDate().toString()+ " - " + controller.getTerms().get(1).getEndDate().toString() );
        term3.setText(controller.getTerms().get(2).getStartDate().toString()+ " - " + controller.getTerms().get(2).getEndDate().toString() );
        term4.setText(controller.getTerms().get(3).getStartDate().toString()+ " - " + controller.getTerms().get(3).getEndDate().toString() );
        
        jCheckTerm1.setSelected(true);
        jCheckTerm2.setSelected(true);
        jCheckTerm3.setSelected(true);
        jCheckTerm4.setSelected(true);
        
        //set combos
        careers = controller.getAllCareers();
        for(Career c: careers){
            jComboC1.addItem(c.getName());
            jComboC2.addItem(c.getName());            
            jComboC3.addItem(c.getName());
            jComboC4.addItem(c.getName());
        }
        
        //get all students
        students = controller.getAllStudents();
        students.forEach(student-> updateTable(student));
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFirst = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jfromLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextNumber = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jbtnRemove = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextLast = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jComboC1 = new javax.swing.JComboBox<>();
        jComboC2 = new javax.swing.JComboBox<>();
        jComboC3 = new javax.swing.JComboBox<>();
        jComboC4 = new javax.swing.JComboBox<>();
        jCheckTerm1 = new javax.swing.JCheckBox();
        jCheckTerm2 = new javax.swing.JCheckBox();
        term1 = new javax.swing.JLabel();
        jCheckTerm3 = new javax.swing.JCheckBox();
        jCheckTerm4 = new javax.swing.JCheckBox();
        term2 = new javax.swing.JLabel();
        term3 = new javax.swing.JLabel();
        term4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(200,75,20));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        setForeground(new java.awt.Color(204, 204, 255));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("First Name");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Email Address");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        jTextFirst.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFirstActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(182, 181, 220));
        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Phone Number", "Start Date", "Career Option"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(0, 86, 200));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Phone number");

        jfromLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jfromLabel.setForeground(new java.awt.Color(0, 0, 102));
        jfromLabel.setText("Availability");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Career #1");

        jTextNumber.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumberActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 102));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 102));
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentdatabase/cropped-OmniLYF-Logo-Final-Transparent.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Career #2");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Career #3");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Career #4");

        jbtnRemove.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jbtnRemove.setForeground(new java.awt.Color(0, 0, 102));
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Last Name");

        jTextLast.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLastActionPerformed(evt);
            }
        });

        jTextEmail.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });

        jComboC1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboC1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboC1ItemStateChanged(evt);
            }
        });
        jComboC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboC1ActionPerformed(evt);
            }
        });

        jComboC2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboC2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboC2ItemStateChanged(evt);
            }
        });
        jComboC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboC2ActionPerformed(evt);
            }
        });

        jComboC3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboC3ActionPerformed(evt);
            }
        });

        jComboC4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jComboC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboC4ActionPerformed(evt);
            }
        });

        jCheckTerm1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckTerm1.setForeground(new java.awt.Color(51, 0, 102));
        jCheckTerm1.setText("Term 1");
        jCheckTerm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTerm1ActionPerformed(evt);
            }
        });

        jCheckTerm2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckTerm2.setForeground(new java.awt.Color(0, 0, 102));
        jCheckTerm2.setText("Term 2");

        term1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        term1.setForeground(new java.awt.Color(0, 0, 102));
        term1.setText("hyg");

        jCheckTerm3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckTerm3.setForeground(new java.awt.Color(0, 0, 102));
        jCheckTerm3.setText("Term 3");
        jCheckTerm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTerm3ActionPerformed(evt);
            }
        });

        jCheckTerm4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCheckTerm4.setForeground(new java.awt.Color(0, 0, 102));
        jCheckTerm4.setText("Term 4");

        term2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        term2.setForeground(new java.awt.Color(0, 0, 102));
        term2.setText("jLabel12");

        term3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        term3.setForeground(new java.awt.Color(0, 0, 102));
        term3.setText("jLabel13");

        term4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        term4.setForeground(new java.awt.Color(0, 0, 102));
        term4.setText("jLabel14");

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 102));
        jButton6.setText("Schedules");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jfromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboC4, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckTerm2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(term2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextLast, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboC1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboC2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboC3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckTerm4)
                                            .addComponent(jCheckTerm3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(term3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(term4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckTerm1)
                                        .addGap(8, 8, 8)
                                        .addComponent(term1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextLast, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckTerm1)
                                    .addComponent(term1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jfromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckTerm2)
                                    .addComponent(term2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckTerm3)
                                    .addComponent(term3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckTerm4)
                            .addComponent(term4))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboC1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboC2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboC3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboC4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnRemove)
                        .addComponent(jButton3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Student Name");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFirstActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed

        try {
            Student student = controller.addStudent(jTextFirst.getText(),jTextLast.getText(),jTextEmail.getText(),jTextNumber.getText());
            controller.addStudentAvailability(student.getId(), jCheckTerm1.isSelected(), jCheckTerm2.isSelected(), jCheckTerm3.isSelected(), jCheckTerm4.isSelected());
            
            //save career choice
            if(jComboC1.getSelectedIndex() != 0)
            {
                int careerId1 = careers.get(jComboC1.getSelectedIndex()- 1).getId();              
                controller.addCareerChoice(student.getId(), careerId1);
                
            }
            if(jComboC2.getSelectedIndex() != 0){
                 int careerId2 = careers.get(jComboC2.getSelectedIndex()- 1).getId();                
                controller.addCareerChoice(student.getId(), careerId2);
            }
            if(jComboC3.getSelectedIndex() != 0){
                int careerId3 = careers.get(jComboC3.getSelectedIndex()-1).getId();
                 controller.addCareerChoice(student.getId(), careerId3);
            }
            if(jComboC4.getSelectedIndex() != 0){
                int careerId4 = careers.get(jComboC4.getSelectedIndex()-1).getId();
                controller.addCareerChoice(student.getId(), careerId4);
            
            }          
            System.out.println("Choices Saved!");
            
            JOptionPane.showMessageDialog(null, "update completed");
            updateTable(student);
        } catch (Exception e) {
            System.out.println(e);
        }     
        
    }//GEN-LAST:event_jbtnAddActionPerformed
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit" + JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
             
        }


    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed

        jTextFirst.setText(null);
        jTextLast.setText(null);
        jTextEmail.setText(null);
        jTextNumber.setText(null);
        jComboC1.setSelectedIndex(0);
        jComboC2.setSelectedIndex(0);
        jComboC3.setSelectedIndex(0);
        jComboC4.setSelectedIndex(0);
        jCheckTerm1.setSelected(true);
        jCheckTerm2.setSelected(true);
        jCheckTerm3.setSelected(true);
        jCheckTerm4.setSelected(true);
        

    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed

        String email =JOptionPane.showInputDialog("Enter student email address");
         controller.deleteStudent(email);
         clearTable();
            
              //get all students
            students = controller.getAllStudents();           
            students.forEach(student-> updateTable(student));
            JOptionPane.showMessageDialog(null,"Successfully removed!");

        
        
             
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private void jTextNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumberActionPerformed

    private void jTextLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLastActionPerformed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed
 
    
    private void jComboC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboC1ActionPerformed
           
        int choice = jComboC1.getSelectedIndex();  
           if(jComboC1.getSelectedIndex()>0 ){
                if(jComboC2.getSelectedIndex()==choice ||jComboC3.getSelectedIndex()==choice ||jComboC4.getSelectedIndex()==choice){
                     jComboC1.setSelectedIndex(0);
                }    
            }
    }//GEN-LAST:event_jComboC1ActionPerformed


    private void jComboC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboC2ActionPerformed
           
          int choice = jComboC2.getSelectedIndex();  
           if(jComboC2.getSelectedIndex()>0 ){
                if(jComboC1.getSelectedIndex()==choice ||jComboC3.getSelectedIndex()==choice ||jComboC4.getSelectedIndex()==choice){
                     jComboC2.setSelectedIndex(0);
                }    
            }
            
    }//GEN-LAST:event_jComboC2ActionPerformed

    private void jComboC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboC3ActionPerformed
            int choice = jComboC3.getSelectedIndex();  
           if(jComboC3.getSelectedIndex()>0 ){
                if(jComboC1.getSelectedIndex()==choice ||jComboC2.getSelectedIndex()==choice ||jComboC4.getSelectedIndex()==choice){
                     jComboC3.setSelectedIndex(0);
                }    
            }
      
    }//GEN-LAST:event_jComboC3ActionPerformed

    private void jComboC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboC4ActionPerformed
       int choice = jComboC4.getSelectedIndex();  
           if(jComboC4.getSelectedIndex()>0 ){
                if(jComboC2.getSelectedIndex()==choice ||jComboC3.getSelectedIndex()==choice ||jComboC1.getSelectedIndex()==choice){
                     jComboC4.setSelectedIndex(0);
                }    
            }
    }//GEN-LAST:event_jComboC4ActionPerformed

    private void jComboC1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboC1ItemStateChanged


    }//GEN-LAST:event_jComboC1ItemStateChanged

    private void jComboC2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboC2ItemStateChanged
      
    }//GEN-LAST:event_jComboC2ItemStateChanged

    private void jCheckTerm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTerm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckTerm1ActionPerformed

    private void jCheckTerm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTerm3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckTerm3ActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ScheduleWindow scheduleWindow;
        try {
            scheduleWindow = new ScheduleWindow();
            scheduleWindow.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(OmnilyfDatabase.class.getName()).log(Level.SEVERE, null, ex);
        }
        
 
    }//GEN-LAST:event_jButton6ActionPerformed
public void clearTable(){
        DefaultTableModel dm = (DefaultTableModel)jTable1.getModel(); 
        dm.setRowCount(0);
        jTable1.revalidate();
    }
    public void updateTable(Student student) {
       
        Object[] col = new Object[4];
        col[0] = student.getFirstname();
        col[1] = student.getLastname();
        col[2] = student.getEmail();
        col[3] = student.getPhone();
       
        DefaultTableModel dm = (DefaultTableModel)jTable1.getModel(); 
        dm.addRow(col);
        dm.fireTableDataChanged();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OmnilyfDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OmnilyfDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OmnilyfDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OmnilyfDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new OmnilyfDatabase().setVisible(true);
                   
                } catch (SQLException ex) {
                    Logger.getLogger(OmnilyfDatabase.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckTerm1;
    private javax.swing.JCheckBox jCheckTerm2;
    private javax.swing.JCheckBox jCheckTerm3;
    private javax.swing.JCheckBox jCheckTerm4;
    private javax.swing.JComboBox<String> jComboC1;
    private javax.swing.JComboBox<String> jComboC2;
    private javax.swing.JComboBox<String> jComboC3;
    private javax.swing.JComboBox<String> jComboC4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFirst;
    private javax.swing.JTextField jTextLast;
    private javax.swing.JTextField jTextNumber;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JLabel jfromLabel;
    private javax.swing.JLabel term1;
    private javax.swing.JLabel term2;
    private javax.swing.JLabel term3;
    private javax.swing.JLabel term4;
    // End of variables declaration//GEN-END:variables
}
